version: '3.8'
services:
  svm_service:
    build: ./Backend/SVM
    ports:
      - "5000:5000"
    networks:
      - app-network

  vgg19_service:
    build: ./Backend/VGG19
    ports:
      - "5001:5001"
    networks:
      - app-network
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
